export enum EnviromentVariablesEnum {
    PORT = 'PORT',
    ENABLE_CORS = 'ENABLE_CORS',
    ENABLE_DOCS = 'ENABLE_DOCS',

    NOSQL_CONNECTION_STRING = 'NOSQL_CONNECTION_STRING',

    JWT_KEY_BACKOFFICE = 'JWT_KEY_BACKOFFICE',
    JWT_KEY_CLIENT = 'JWT_KEY_CLIENT',

    JWT_EXPIRATION = 'JWT_EXPIRATION',

    SENDGRID_EMAIL_SENDER = 'SENDGRID_EMAIL_SENDER',
    SENDGRID_API_KEY = 'SENDGRID_API_KEY',

    PAYLOAD_ENCRYPT_KEY = 'PAYLOAD_ENCRYPT_KEY',


    AWS_REGION = 'AWS_REGION',
    AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
    AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',

    S3_BUCKET_USER_PHOTO = 'S3_BUCKET_USER_PHOTO',

    S3_BUCKET_DOCUMENTS = 'S3_BUCKET_DOCUMENTS',
    
    S3_BUCKET= 'S3_BUCKET'
}